// SEO Metadata
import type { Metadata } from "next";

// Sidebar
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/app-sidebar";

// Toasters
import { Toaster } from "@/components/ui/sonner";

// Stackframe
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";

// Fonts
import { Geist_Mono, Nunito } from "next/font/google";

// global CSS
import "./globals.css";
import { SiteHeader } from "@/components/site-header";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${geistMono.variable} antialiased`}>
        <StackProvider app={stackClientApp}>
          <StackTheme>
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <SiteHeader />
                {children}
              </main>
              <Toaster closeButton />
            </SidebarProvider>
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
