// SEO Metadata
import type { Metadata } from "next";

// Toasters
import { Toaster } from "@/components/ui/sonner";

// Stackframe
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";

// Fonts
import { Geist_Mono, Nunito } from "next/font/google";

// global CSS
import "./globals.css";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.variable} ${geistMono.variable} antialiased`}>
        <StackProvider app={stackClientApp}>
          <StackTheme>
            {children}
            <Toaster closeButton />
          </StackTheme>
        </StackProvider>
      </body>
    </html>
  );
}
